apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-frontend
  template:
    metadata:
      labels:
        app: taskmanager-frontend
    spec:
      containers:
      - name: frontend
        image: omanthi/taskmanager-frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          value: "http://taskmanager-backend:4000/api/v1"
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskmanager-backend
  template:
    metadata:
      labels:
        app: taskmanager-backend
    spec:
      containers:
      - name: backend
        image: omanthi/taskmanager-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: taskmanager-secrets
              key: mongo-uri
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: taskmanager-secrets
              key: jwt-secret
        - name: COOKIE_EXPIRE
          value: "7"
        - name: CLOUDINARY_CLIENT_NAME
          valueFrom:
            secretKeyRef:
              name: taskmanager-secrets
              key: cloudinary-name
        - name: CLOUDINARY_CLIENT_API
          valueFrom:
            secretKeyRef:
              name: taskmanager-secrets
              key: cloudinary-api
        - name: CLOUDINARY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: taskmanager-secrets
              key: cloudinary-secret
        - name: FRONTEND_URL
          value: "http://taskmanager-frontend:5173"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
