#version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=development
      - PORT=4000
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:4000/api
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
