apiVersion: v1
kind: Service
metadata:
  name: taskmanager-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5173
  selector:
    app: taskmanager-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-backend
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: taskmanager-backend
