apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
  labels:
    app: taskmanager
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"  # Use Network Load Balancer for better performance
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
spec:
  type: LoadBalancer
  ports:
  - name: frontend
    port: 80
    targetPort: 5173
    protocol: TCP
  - name: backend
    port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app: taskmanager
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-backend-service
  labels:
    app: taskmanager-backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
spec:
  type: ClusterIP
  ports:
  - name: backend
    port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app: taskmanager
