apiVersion: v1
kind: Service
metadata:
  name: taskmanager-service
  labels:
    app: taskmanager
spec:
  type: ClusterIP  # Change from LoadBalancer to ClusterIP
  ports:
  - port: 80
    targetPort: 5173  # If you're still using Vite's dev server
    name: frontend
  selector:
    app: taskmanager
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-backend-service
  labels:
    app: taskmanager-backend
spec:
  type: ClusterIP
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: taskmanager
